### ISSUE TITLE
Build error: -lcyw43_driver_base: No such file or directory

### ISSUE THREAD

**Issue by v-mwalk** [krzmaz/pico-w-webserver-example#12]
Ubuntu with Build chain installed as per Pico C/C++ doco; Wifi Scan example project builds and runs okay.

I currently dont know enough about CMake/Build process be able to debug the build process yet, except for the cmake build.

Vanilla instance of pico-w-webserver-example

Build within vscode OR using ./build.sh results in Build error:-

```
[build] [ 98%] Building C object src/CMakeFiles/pico_w_webserver.dir/home/mat/pico/pico-sdk/src/rp2_common/hardware_adc/adc.c.obj
[build] [100%] Linking CXX executable pico_w_webserver.elf
[build] /usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: cannot find -lcyw43_driver_base: No such file or directory
[build] collect2: error: ld returned 1 exit status
[build] gmake[2]: *** [src/CMakeFiles/pico_w_webserver.dir/build.make:2967: src/pico_w_webserver.elf] Error 1
[build] gmake[1]: *** [CMakeFiles/Makefile2:1638: src/CMakeFiles/pico_w_webserver.dir/all] Error 2
[build] gmake: *** [Makefile:91: all] Error 2
[proc] The command: /usr/bin/cmake --build /home/mat/pico/pico-w-webserver-example-main/build --config Debug --target all -j 10 -- exited with code: 2
```

If it helps, cmake tracing shows;

Running with expanded trace output on.
-- Found Perl: /usr/bin/perl (found version "5.34.0") 
-- Defaulting build type to 'Release' since not specified.
-- The C compiler identification is GNU 10.3.1
-- The CXX compiler identification is GNU 10.3.1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/arm-none-eabi-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/arm-none-eabi-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/arm-none-eabi-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /usr/bin/python3.10 (found version "3.10.6") found components: Interpreter 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mat/pico/pico-w-webserver-example-main/build

**Comment by krzmaz** [comment]
Hi, happy you're interested in the project and sorry for the inconvenience! The build logic naively downloads the latest Pico-SDK, which had some changes in 1.5.0 release. I've added a quick fix, it should work now 😄

**Comment by v-mwalk** [comment]
Oh stop - no inconvenience here!  You have a great project; I'm the one who should be sorry, for not knowing enough about the Pico toolchain yet :-)

Thanks Krzysiek I'll have a play :-)
